USE [TMD]
GO

/****** Object:  StoredProcedure [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]    Script Date: 03/13/2013 02:55:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]
@CODIGO_PROYECTO INT,
@CODIGO_LINEABASE INT
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		A.CODIGO AS CODIGO_SOLICITUD,
		A.NOMBRE AS NOMBRE_SOLICITUD,
		B.CODIGO,
		B.NOMBRE,
		B.ESTADO,
		B.FECHA_REGISTRO,
		B.FECHA_APROBACION
	FROM 
		dbo.SOLICITUD_CAMBIO AS A LEFT JOIN dbo.INFORME_CAMBIO AS B
	ON 
		B.CODIGO_SOLICITUD = A.CODIGO 
	WHERE 
		A.ESTADO = 1 AND A.CODIGO_PROYECTO = @CODIGO_PROYECTO AND A.CODIGO_LINEA_BASE = @CODIGO_LINEABASE
		
	SET NOCOUNT OFF;
END


GO


