IF((SELECT Object_Id('dbo.USP_ORDEN_CAMBIO_SEL_CODIGO')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_ORDEN_CAMBIO_SEL_CODIGO
END
GO

CREATE PROCEDURE dbo.USP_ORDEN_CAMBIO_SEL_CODIGO
@CODIGO INT 
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT  
		OC.CODIGO, OC.NOMBRE AS NOMBRE_ORDEN, OC.CODIGO_INFORME, IC.NOMBRE, 
		OC.CODIGO_USUARIO_REG, OC.FECHA_REGISTRO, OC.PRIORIDAD, 
		OC.CODIGO_USUARIO_ASIGNADO, U.NOMBRE AS NOMBRE_USUARIO, OC.NOMBRE_ARCHIVO,
		P.CODIGO_PROYECTO, P.NOMBRE AS NOMBRE_PROYECTO,
		LB.CODIGO AS CODIGO_LINEA, LB.NOMBRE AS NOMBRE_LINEA
	FROM
		dbo.ORDEN_CAMBIO AS OC
		INNER JOIN dbo.INFORME_CAMBIO AS IC
		ON IC.CODIGO = OC.CODIGO_INFORME
		INNER JOIN dbo.SOLICITUD_CAMBIO AS S
		ON S.CODIGO = IC.CODIGO_SOLICITUD
		INNER JOIN dbo.PROYECTO AS P
		ON P.CODIGO_PROYECTO = S.CODIGO_PROYECTO
		INNER JOIN dbo.LINEA_BASE AS LB
		ON LB.CODIGO = S.CODIGO_LINEA_BASE
		INNER JOIN dbo.USUARIO AS U
		ON U.CODIGO = OC.CODIGO_USUARIO_ASIGNADO
	WHERE
		OC.CODIGO = @CODIGO
		
	SET NOCOUNT OFF;
END
GO