USE [TMD]
GO

/****** Object:  StoredProcedure [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]    Script Date: 03/14/2013 02:15:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]
GO

USE [TMD]
GO

/****** Object:  StoredProcedure [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]    Script Date: 03/14/2013 02:15:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[USP_INFORME_CAMBIO_SEL_PROYECTO_LINEABASE]
@CODIGO_PROYECTO INT,
@CODIGO_LINEABASE INT
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		A.CODIGO AS CODIGO_SOLICITUD,
		A.NOMBRE AS NOMBRE_SOLICITUD,
		A.FECHA_APROBACION AS SOLICITUD_FECHA_APROBACION,
		B.CODIGO,
		B.NOMBRE,
		B.ESTADO,
		B.FECHA_REGISTRO,
		B.FECHA_APROBACION,
		B.MOTIVO,
		B.NOMBRE_ARCHIVO
	FROM 
		dbo.SOLICITUD_CAMBIO AS A LEFT JOIN dbo.INFORME_CAMBIO AS B
	ON 
		B.CODIGO_SOLICITUD = A.CODIGO 
	WHERE 
		A.ESTADO = 2 AND A.CODIGO_PROYECTO = @CODIGO_PROYECTO AND A.CODIGO_LINEA_BASE = @CODIGO_LINEABASE
		
	SET NOCOUNT OFF;
END


GO


