USE [TMD]
GO

/****** Object:  StoredProcedure [dbo].[USP_INFORME_CAMBIO_INS]    Script Date: 03/14/2013 02:26:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_INFORME_CAMBIO_INS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_INFORME_CAMBIO_INS]
GO

USE [TMD]
GO

/****** Object:  StoredProcedure [dbo].[USP_INFORME_CAMBIO_INS]    Script Date: 03/14/2013 02:26:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_INFORME_CAMBIO_INS]
@CODIGO INT OUTPUT,
@CODIGO_SOLICITUD INT,
@CODIGO_USUARIO INT,
@FECHA_REGISTRO DATETIME,
@ESTADO INT,
@ESTIMACION_COSTO VARCHAR(200),
@ESTIMACION_ESFUERZO VARCHAR(200),
@RECURSOS VARCHAR(200),
@RUTA_ARCHIVO VARCHAR(MAX) OUTPUT,
@TRANSACTION_CONTEXT VARBINARY(MAX) OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

	INSERT INTO [dbo].[INFORME_CAMBIO] (
		CODIGO,
		CODIGO_SOLICITUD, 
		CODIGO_USUARIO, 
		FECHA_REGISTRO, 
		ESTADO,
		ESTIMACION_COSTO,
		ESTIMACION_ESFUERZO,
		RECURSOS,
		DATA)
	VALUES
		(@CODIGO,
		@CODIGO_SOLICITUD, 
		@CODIGO_USUARIO, 
		@FECHA_REGISTRO, 
		@ESTADO,
		@ESTIMACION_COSTO,
		@ESTIMACION_ESFUERZO,
		@RECURSOS,
		CAST('' AS VARBINARY(MAX)));

	SELECT 
		@RUTA_ARCHIVO = DATA.PathName(),
		@TRANSACTION_CONTEXT = GET_FILESTREAM_TRANSACTION_CONTEXT()
	FROM 
		dbo.INFORME_CAMBIO
	WHERE 
		CODIGO = @CODIGO;

	SET NOCOUNT OFF;

END

GO


