IF((SELECT Object_Id('dbo.USP_SOLICITUD_CAMBIO_SEL_PROYECTO_LINEABASE')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_SOLICITUD_CAMBIO_SEL_PROYECTO_LINEABASE
END
GO

CREATE PROCEDURE dbo.USP_SOLICITUD_CAMBIO_SEL_PROYECTO_LINEABASE
@CODIGO_PROYECTO INT,
@CODIGO_LINEABASE INT,
@ESTADO VARCHAR(2),
@PRIORIDAD INT
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		SC.CODIGO,
		SC.NOMBRE,
		SC.CODIGO_PROYECTO,
		SC.CODIGO_LINEA_BASE,
		SC.CODIGO_USUARIO,
		SC.FECHA_APROBACION,
		SC.FECHA_REGISTRO,
		SC.ESTADO,
		SC.CODIGO_ECS,
		SC.PRIORIDAD,
		SC.MOTIVO,
		P.NOMBRE AS PROYECTO,
		LB.NOMBRE AS LINEA_BASE,
		E.NOMBRE AS ELEMENTO,
		SC.NOMBRE_ARCHIVO
	FROM
		dbo.SOLICITUD_CAMBIO AS SC
		INNER JOIN dbo.PROYECTO AS P
		ON SC.CODIGO_PROYECTO = P.CODIGO_PROYECTO
		INNER JOIN dbo.LINEA_BASE AS LB
		ON SC.CODIGO_LINEA_BASE = LB.CODIGO
		INNER JOIN dbo.ELEMENTO_CONFIGURACION AS E
		ON SC.CODIGO_ECS = E.CODIGO
	WHERE
		SC.CODIGO_PROYECTO = @CODIGO_PROYECTO
		AND (@CODIGO_LINEABASE = 0 OR SC.CODIGO_LINEA_BASE = @CODIGO_LINEABASE)
		AND (@ESTADO = '0' OR SC.ESTADO = @ESTADO)
		AND (@PRIORIDAD = 0 OR SC.PRIORIDAD = @PRIORIDAD)
	ORDER BY SC.CODIGO DESC;
		
	SET NOCOUNT OFF;
END
GO