IF((SELECT Object_Id('dbo.USP_SOLICITUD_CAMBIO_APROBAR_UPD')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_SOLICITUD_CAMBIO_APROBAR_UPD
END
GO

CREATE PROCEDURE [dbo].USP_SOLICITUD_CAMBIO_APROBAR_UPD
@CODIGO INT,
@MOTIVO VARCHAR(200),
@ESTADO VARCHAR(2)
AS
BEGIN

	SET NOCOUNT ON;

	UPDATE 
		[dbo].SOLICITUD_CAMBIO
	SET
		MOTIVO = @MOTIVO,
		ESTADO = @ESTADO
	WHERE
	CODIGO = @CODIGO;

	SET NOCOUNT OFF;

END
GO