IF((SELECT Object_Id('dbo.USP_PROYECO_FASE_COD_PROYECTO_FASE')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_PROYECO_FASE_COD_PROYECTO_FASE
END
GO

CREATE PROCEDURE [dbo].USP_PROYECO_FASE_COD_PROYECTO_FASE  
@CODIGO_PROYECTO INT,  
@CODIGO_FASE INT  
AS  
BEGIN  
  
 SET NOCOUNT ON;  
  
 SELECT  
  PF.CODIGO,   
  PF.CODIGO_PROYECTO,   
  PF.CODIGO_FASE,   
  PF.FECHA_INICIO,   
  PF.FECHA_FIN,
  P.FECHA_FIN AS FECHA_FIN_PROYECTO
 FROM  
  dbo.PROYECTO_FASE  AS PF
  INNER JOIN dbo.PROYECTO AS P
  ON PF.CODIGO_PROYECTO = P.CODIGO_PROYECTO
 WHERE  
  PF.CODIGO_PROYECTO = @CODIGO_PROYECTO  
  AND PF.CODIGO_FASE = @CODIGO_FASE;  
  
 SET NOCOUNT OFF;  
  
END  
GO