#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.ACP.AccesoDatos.Implementacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ACPBD")]
	public partial class DAArchivoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAC_ARCHIVO(AC_ARCHIVO instance);
    partial void UpdateAC_ARCHIVO(AC_ARCHIVO instance);
    partial void DeleteAC_ARCHIVO(AC_ARCHIVO instance);
    #endregion
		
		public DAArchivoDataContext() : 
				base(global::TMD.ACP.AccesoDatos.Properties.Settings.Default.ACPBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DAArchivoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAArchivoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAArchivoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAArchivoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AC_ARCHIVO> AC_ARCHIVOs
		{
			get
			{
				return this.GetTable<AC_ARCHIVO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AC_ARCHIVO")]
	public partial class AC_ARCHIVO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idArchivo;
		
		private System.Data.Linq.Binary _dataBinaria;
		
		private string _nombreArchivo;
		
		private string _mimeType;
		
		private System.DateTime _fechaCarga;
		
		private System.Nullable<int> _idOrigen;
		
		private System.Nullable<char> _tipoOrigen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidArchivoChanging(int value);
    partial void OnidArchivoChanged();
    partial void OndataBinariaChanging(System.Data.Linq.Binary value);
    partial void OndataBinariaChanged();
    partial void OnnombreArchivoChanging(string value);
    partial void OnnombreArchivoChanged();
    partial void OnmimeTypeChanging(string value);
    partial void OnmimeTypeChanged();
    partial void OnfechaCargaChanging(System.DateTime value);
    partial void OnfechaCargaChanged();
    partial void OnidOrigenChanging(System.Nullable<int> value);
    partial void OnidOrigenChanged();
    partial void OntipoOrigenChanging(System.Nullable<char> value);
    partial void OntipoOrigenChanged();
    #endregion
		
		public AC_ARCHIVO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArchivo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idArchivo
		{
			get
			{
				return this._idArchivo;
			}
			set
			{
				if ((this._idArchivo != value))
				{
					this.OnidArchivoChanging(value);
					this.SendPropertyChanging();
					this._idArchivo = value;
					this.SendPropertyChanged("idArchivo");
					this.OnidArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataBinaria", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary dataBinaria
		{
			get
			{
				return this._dataBinaria;
			}
			set
			{
				if ((this._dataBinaria != value))
				{
					this.OndataBinariaChanging(value);
					this.SendPropertyChanging();
					this._dataBinaria = value;
					this.SendPropertyChanged("dataBinaria");
					this.OndataBinariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreArchivo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreArchivo
		{
			get
			{
				return this._nombreArchivo;
			}
			set
			{
				if ((this._nombreArchivo != value))
				{
					this.OnnombreArchivoChanging(value);
					this.SendPropertyChanging();
					this._nombreArchivo = value;
					this.SendPropertyChanged("nombreArchivo");
					this.OnnombreArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mimeType", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mimeType
		{
			get
			{
				return this._mimeType;
			}
			set
			{
				if ((this._mimeType != value))
				{
					this.OnmimeTypeChanging(value);
					this.SendPropertyChanging();
					this._mimeType = value;
					this.SendPropertyChanged("mimeType");
					this.OnmimeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCarga", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCarga
		{
			get
			{
				return this._fechaCarga;
			}
			set
			{
				if ((this._fechaCarga != value))
				{
					this.OnfechaCargaChanging(value);
					this.SendPropertyChanging();
					this._fechaCarga = value;
					this.SendPropertyChanged("fechaCarga");
					this.OnfechaCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrigen", DbType="Int")]
		public System.Nullable<int> idOrigen
		{
			get
			{
				return this._idOrigen;
			}
			set
			{
				if ((this._idOrigen != value))
				{
					this.OnidOrigenChanging(value);
					this.SendPropertyChanging();
					this._idOrigen = value;
					this.SendPropertyChanged("idOrigen");
					this.OnidOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoOrigen", DbType="Char(1)")]
		public System.Nullable<char> tipoOrigen
		{
			get
			{
				return this._tipoOrigen;
			}
			set
			{
				if ((this._tipoOrigen != value))
				{
					this.OntipoOrigenChanging(value);
					this.SendPropertyChanging();
					this._tipoOrigen = value;
					this.SendPropertyChanged("tipoOrigen");
					this.OntipoOrigenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
