<?xml version="1.0" encoding="utf-8"?><Database Name="ACPBD" Class="DAArchivoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SVRRAUL;Initial Catalog=ACPBD;User ID=sa" SettingsObjectName="TMD.ACP.AccesoDatos.Properties.Settings" SettingsPropertyName="ACPBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AC_ARCHIVO" Member="AC_ARCHIVOs">
    <Type Name="AC_ARCHIVO">
      <Column Name="idArchivo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dataBinaria" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="nombreArchivo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="mimeType" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaCarga" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idOrigen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipoOrigen" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>