//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pagina {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pagina() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMD.Strings.Pagina", typeof(Pagina).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActualizarLineaBase.aspx?idProyecto={0}&amp;idFase=0&amp;lectura=0.
        /// </summary>
        public static string ActLineaBaseEscritura {
            get {
                return ResourceManager.GetString("ActLineaBaseEscritura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActualizarLineaBase.aspx?idProyecto={0}&amp;idFase={1}&amp;lectura=1.
        /// </summary>
        public static string ActLineaBaseLectura {
            get {
                return ResourceManager.GetString("ActLineaBaseLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}.aspx?idProyecto={0}&amp;idFase={1}&amp;lectura=0.
        /// </summary>
        public static string ActualizarPagina {
            get {
                return ResourceManager.GetString("ActualizarPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Vistas/CF/LineaBase/ListaLineaBase.aspx.
        /// </summary>
        public static string LineaBase {
            get {
                return ResourceManager.GetString("LineaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Error/NoPermitido.aspx.
        /// </summary>
        public static string NoPermitido {
            get {
                return ResourceManager.GetString("NoPermitido", resourceCulture);
            }
        }
    }
}
