ALTER TABLE dbo.ORDEN_CAMBIO
ADD NOMBRE_ARCHIVO VARCHAR(50) NULL;
GO

ALTER TABLE dbo.ORDEN_CAMBIO
ADD EXTENSION CHAR(3) NULL;
GO

ALTER TABLE dbo.ORDEN_CAMBIO
ADD NOMBRE VARCHAR(50) NULL;
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORDEN_CAMBIO_PRIORIDAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDEN_CAMBIO]'))
ALTER TABLE [dbo].[ORDEN_CAMBIO] DROP CONSTRAINT [FK_ORDEN_CAMBIO_PRIORIDAD]
GO

ALTER TABLE dbo.ORDEN_CAMBIO
DROP COLUMN CODIGO_PRIORIDAD
GO

ALTER TABLE dbo.ORDEN_CAMBIO
ADD PRIORIDAD INT  NULL
GO

ALTER TABLE dbo.ORDEN_CAMBIO
DROP COLUMN ESTADO
GO

ALTER TABLE dbo.ORDEN_CAMBIO
DROP COLUMN FECHA_APROBACION
GO

ALTER TABLE dbo.ORDEN_CAMBIO
DROP COLUMN DATA
GO

ALTER TABLE dbo.ORDEN_CAMBIO
ADD DATA VARBINARY(MAX) FILESTREAM  NULL
GO