IF((SELECT Object_Id('dbo.USP_ORDEN_CAMBIO_INS')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_ORDEN_CAMBIO_INS
END
GO

CREATE PROCEDURE dbo.USP_ORDEN_CAMBIO_INS
@CODIGO INT OUTPUT,
@NOMBRE VARCHAR(50),
@CODIGO_INFORME INT,
@CODIGO_USUARIO_REG INT,
@FECHA_REGISTRO DATE,
@CODIGO_USUARIO_ASIGNADO INT,
@PRIORIDAD INT
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO dbo.ORDEN_CAMBIO(
		NOMBRE,
		CODIGO_INFORME,
		CODIGO_USUARIO_REG,
		FECHA_REGISTRO,
		CODIGO_USUARIO_ASIGNADO,
		PRIORIDAD)
	VALUES(
		@NOMBRE,
		@CODIGO_INFORME,
		@CODIGO_USUARIO_REG,
		@FECHA_REGISTRO,
		@CODIGO_USUARIO_ASIGNADO,
		@PRIORIDAD
	);
	
	SET @CODIGO = SCOPE_IDENTITY();
	
	SET NOCOUNT OFF;
END
GO