IF((SELECT Object_Id('dbo.USP_LINEA_BASE_INS')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_LINEA_BASE_INS
END
GO

CREATE PROCEDURE [dbo].USP_LINEA_BASE_INS
@CODIGO INT OUTPUT,
@CODIGO_PROYECTO_FASE INT,
@NOMBRE VARCHAR(50),
@DESCRIPCION VARCHAR(100)
AS
BEGIN

	SET NOCOUNT ON;

	INSERT INTO [dbo].[LINEA_BASE](
		CODIGO_PROYECTO_FASE, 
		NOMBRE, 
		DESCRIPCION, 
		FECHA_CREACION, 
		ESTADO)
	VALUES
		(@CODIGO_PROYECTO_FASE, 
		@NOMBRE, 
		@DESCRIPCION, 
		GETDATE(), 
		'1');
		
	SET @CODIGO = SCOPE_IDENTITY();

	SET NOCOUNT OFF;

END
