IF((SELECT Object_Id('dbo.USP_ORDEN_CAMBIO_SEL_ARCHIVO')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_ORDEN_CAMBIO_SEL_ARCHIVO
END
GO

CREATE PROCEDURE [dbo].USP_ORDEN_CAMBIO_SEL_ARCHIVO
@CODIGO INT
AS
BEGIN
	SET NOCOUNT ON;	
	
	SELECT
		NOMBRE_ARCHIVO,
		DATA.PathName() AS RUTA_ARCHIVO,
		GET_FILESTREAM_TRANSACTION_CONTEXT() AS TRANSACTION_CONTEXT
	FROM 
		dbo.ORDEN_CAMBIO
	WHERE 
		CODIGO = @CODIGO;

	SET NOCOUNT OFF;
END
GO