IF((SELECT Object_Id('dbo.USP_SOLICITUD_CAMBIO_UPD_ARCHIVO')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_SOLICITUD_CAMBIO_UPD_ARCHIVO
END
GO

CREATE  PROCEDURE [dbo].USP_SOLICITUD_CAMBIO_UPD_ARCHIVO
@CODIGO INT,
@NOMBRE_ARCHIVO VARCHAR(50),
@EXTENSION CHAR(3),
@RUTA_ARCHIVO VARCHAR(MAX) OUTPUT,
@TRANSACTION_CONTEXT VARBINARY(MAX) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;	
	
	UPDATE 
		dbo.SOLICITUD_CAMBIO
	SET 
		NOMBRE_ARCHIVO = @NOMBRE_ARCHIVO,
		EXTENSION = @EXTENSION,
		DATA = CAST('' AS VARBINARY(MAX))
	WHERE
		CODIGO = @CODIGO;
		
	SELECT 
		@RUTA_ARCHIVO = DATA.PathName(),
		@TRANSACTION_CONTEXT = GET_FILESTREAM_TRANSACTION_CONTEXT()
	FROM 
		dbo.SOLICITUD_CAMBIO
	WHERE 
		CODIGO = @CODIGO;

	SET NOCOUNT OFF;
END
GO
