IF((SELECT Object_Id('dbo.USP_ORDEN_CAMBIO_INS')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_ORDEN_CAMBIO_INS
END
GO

CREATE PROCEDURE dbo.USP_ORDEN_CAMBIO_INS
@CODIGO INT OUTPUT,
@CODIGO_INFORME INT,
@CODIGO_USUARIO_REG INT,
@FECHA_REGISTRO DATE,
@FECHA_APROBACION DATE,
@CODIGO_PRIORIDAD INT,
@CODIGO_USUARIO_ASIGNADO INT,
@ESTADO VARCHAR(2)
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO dbo.ORDEN_CAMBIO(
		CODIGO_INFORME,
		CODIGO_USUARIO_REG,
		FECHA_REGISTRO,
		FECHA_APROBACION,
		CODIGO_PRIORIDAD,
		CODIGO_USUARIO_ASIGNADO,
		ESTADO)
	VALUES(
		@CODIGO_INFORME,
		@CODIGO_USUARIO_REG,
		@FECHA_REGISTRO,
		@FECHA_APROBACION,
		@CODIGO_PRIORIDAD,
		@CODIGO_USUARIO_ASIGNADO,
		@ESTADO
	);
	
	SET @CODIGO = SCOPE_IDENTITY();
	
	SET NOCOUNT OFF;
END
GO