IF((SELECT Object_Id('dbo.USP_SOLICITUD_CAMBIO_INS')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_SOLICITUD_CAMBIO_INS
END
GO

CREATE PROCEDURE dbo.USP_SOLICITUD_CAMBIO_INS
AS
BEGIN
	SET NOCOUNT ON;	
	
	SET NOCOUNT OFF;
END
GO