IF((SELECT Object_Id('dbo.USP_LINEA_BASE_DET_SEL_CODIGO')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_LINEA_BASE_DET_SEL_CODIGO
END
GO

CREATE PROCEDURE dbo.USP_LINEA_BASE_DET_SEL_CODIGO
@CODIGO INT
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		LBD.CODIGO, 
		LBD.CODIGO_ECS, 
		EC.NOMBRE AS ECS_NOMBRE,
		EC.TIPO,
		LBD.CODIGO_RESPONSABLE, 
		LBD.FECHA_ENTREGA, 
		LBD.VERSION_MENOR, 
		LBD.VERSION_MAYOR, 
		LBD.CODIGO_LINEA_BASE,
		LBD.NOMBRE,
		LBD.EXTENSION,
		PF.FECHA_FIN
	FROM
		dbo.LINEA_BASE_DETALLE AS LBD
		INNER JOIN dbo.LINEA_BASE AS LB
		ON LBD.CODIGO_LINEA_BASE = LB.CODIGO
		INNER JOIN dbo.PROYECTO_FASE AS PF
		ON LB.CODIGO_PROYECTO_FASE = PF.CODIGO
		INNER JOIN dbo.ELEMENTO_CONFIGURACION AS EC
		ON LBD.CODIGO_ECS = EC.CODIGO
	WHERE
		LBD.CODIGO = @CODIGO;
		

	SET NOCOUNT OFF;

END
GO