IF((SELECT Object_Id('dbo.USP_SOLICITUD_CAMBIO_INS')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_SOLICITUD_CAMBIO_INS
END
GO

CREATE PROCEDURE dbo.USP_SOLICITUD_CAMBIO_INS
@CODIGO INT OUTPUT,
@NOMBRE VARCHAR(50),
@CODIGO_PROYECTO INT,
@CODIGO_LINEABASE INT,
@CODIGO_USUARIO INT,
@FECHA_REGISTRO DATE,
@ESTADO VARCHAR(2),
@CODIGO_ECS INT,
@PRIORIDAD INT
AS
BEGIN
	SET NOCOUNT ON;	
	
	INSERT INTO dbo.SOLICITUD_CAMBIO(
		NOMBRE, 
		CODIGO_PROYECTO, 
		CODIGO_LINEA_BASE, 
		CODIGO_USUARIO, 
		FECHA_REGISTRO, 
		ESTADO, 
		CODIGO_ECS, 
		PRIORIDAD)
	VALUES(
		@NOMBRE,
		@CODIGO_PROYECTO,
		@CODIGO_LINEABASE,
		@CODIGO_USUARIO,
		@FECHA_REGISTRO,
		@ESTADO,
		@CODIGO_ECS,
		@PRIORIDAD
	);
	
	SET @CODIGO = SCOPE_IDENTITY();
	
	SET NOCOUNT OFF;
END
GO