IF((SELECT Object_Id('dbo.USP_USUARIO_SEL_CODIGO_ROL')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_USUARIO_SEL_CODIGO_ROL
END
GO

CREATE PROCEDURE [dbo].[USP_USUARIO_SEL_CODIGO_ROL]
@ROL CHAR(2)
AS
BEGIN
	SET NOCOUNT ON;	
	
	SELECT
		U.CODIGO,
		U.NOMBRE,
		U.ROL
	FROM
		dbo.USUARIO AS U
	WHERE
		@ROL = '' OR U.ROL = @ROL;

	SET NOCOUNT OFF;
END

GO