IF((SELECT Object_Id('dbo.USP_LINEA_BASE_SEL_CODIGO')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_LINEA_BASE_SEL_CODIGO
END
GO

CREATE PROCEDURE [dbo].USP_LINEA_BASE_SEL_CODIGO
@CODIGO INT
AS  
BEGIN  
  
 SET NOCOUNT ON;  
  
 SELECT  
  LB.CODIGO,  
  LB.CODIGO_PROYECTO_FASE,  
  LB.NOMBRE,  
  F.NOMBRE AS NOMBRE_FASE,  
  F.CODIGO AS CODIGO_FASE,  
  PF.FECHA_INICIO,  
  PF.FECHA_FIN,  
  LB.DESCRIPCION,  
  LB.ESTADO,  
  LB.FECHA_LIBERACION  
 FROM  
  dbo.LINEA_BASE AS LB  
  INNER JOIN dbo.PROYECTO_FASE AS PF  
  ON LB.CODIGO_PROYECTO_FASE = PF.CODIGO  
  INNER JOIN dbo.FASE AS F  
  ON PF.CODIGO_FASE = F.CODIGO  
 WHERE  
  LB.CODIGO = @CODIGO; 
  
 SET NOCOUNT OFF;  
  
END  
GO