IF((SELECT Object_Id('dbo.USP_USUARIO_SEL_LOGIN')) IS NOT NULL)
BEGIN
	DROP PROCEDURE dbo.USP_USUARIO_SEL_LOGIN
END
GO

CREATE PROCEDURE dbo.USP_USUARIO_SEL_LOGIN
@LOGIN VARCHAR(10)
AS
BEGIN

	SELECT
		U.CODIGO,
		U.NOMBRE,
		U.ROL
	FROM
		dbo.USUARIO AS U
	WHERE
		U.LOGIN = @LOGIN;
	
END
GO